AAT_infrastructure/InventoryServer/grails-app/domain/com/wdc/SerialServer.groovy
package com.wdc


class SerialServer {
	String ipAddress
	String port
	Date dateCreated
	Date lastUpdated
	
	static transients = ['device']
	
	static mapping = {
		id column:'serialServerId'
	}
	
	static constraints = {
		port(unique:"ipAddress",shared:"portShared")
		ipAddress(shared:"ipAddressShared")
	}
	
	Device getDevice() {
		def c = Device.createCriteria()
		def device = c.get {
			serialServer {
				eq('id',this.id)
			}
		}		
	}
	

	String toString(){		
		"${this.ipAddress}:${this.port}"
	}
    
}

AAT_infrastructure/InventoryServer/grails-app/controllers/com/wdc/SerialServerController.groovy
package com.wdc

import com.wdc.response.*
import grails.rest.*
import grails.converters.*
import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class SerialServerController extends AbstractInventoryController{
	
	def serialServerService

	SerialServerController(){
		super(SerialServer)
	}

    def show(SerialServer serialServerInstance) {
        if(super.show(serialServerInstance)){
			def messageResponse = new GetSerialServerResponse(status:Status.SUCCESS,serialServer:serialServerInstance)
			withFormat{
				html {respond serialServerInstance}
				json {render text:messageResponse as JSON,status:OK,contentType:"application/json"}
				xml {render text:messageResponse as XML,status:OK,contentType:"text/xml"}
			}
			
		}
    }

    def create() {
        super.create(new SerialServer(params))
    }

    @Transactional
    def save(SerialServer serialServerInstance) {
		if(!super.save(serialServerInstance)) return
        
		if(renderErrors(serialServerInstance,'create')) return
		serialServerInstance.save flush:true
		if(renderErrors(serialServerInstance,'create')) return

		def messageResponse = new GetSerialServerResponse(status:Status.SUCCESS,serialServer:serialServerInstance)
        withFormat {
            html {
                flash.message = message(code: 'default.created.message', args: [message(code: 'serialServer.label', default: 'SerialServer'), serialServerInstance])
                redirect serialServerInstance
            }
            json {render text:messageResponse as JSON,status:CREATED,contentType:"application/json"}
			xml {render text:messageResponse as XML,status:CREATED,contentType:"text/xml"}
        }
    }

    def edit(SerialServer serialServerInstance) {
        super.edit(serialServerInstance)
    }

    @Transactional
    def update(SerialServer serialServerInstance) {
		if(!super.update(serialServerInstance)) return
        
        if(renderErrors(serialServerInstance,'edit')) return
        serialServerInstance.save flush:true
		if(renderErrors(serialServerInstance,'edit')) return

		def messageResponse = new GetSerialServerResponse(status:Status.SUCCESS,serialServer:serialServerInstance)
        withFormat {
            html {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'serialServer.label', default: 'SerialServer'),serialServerInstance])
                redirect serialServerInstance
            }
            json {render text:messageResponse as JSON,status:OK,contentType:"application/json"}
			xml {render text:messageResponse as XML,status:OK,contentType:"text/xml"}
        }
    }

    @Transactional
    def delete(SerialServer serialServerInstance) {
		if(!super.delete(serialServerInstance)) return
				
        serialServerService.delete(serialServerInstance)
		if(renderErrors(serialServerInstance,'show')) return
		
		def messageResponse = new MessageResponse(status:Status.SUCCESS,message:'Serial Server has been successfully deleted')
        withFormat {
            html {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'serialServer.label', default: 'SerialServer'), serialServerInstance])
                redirect action:"index", method:"GET"
            }
            json {render text:messageResponse as JSON, status:OK,contentType:"application/json"}
			xml {render text:messageResponse as XML, status:OK,contentType:"text/xml"}
        }
    }
	
}

AAT_infrastructure/InventoryServer/grails-app/views/serialServer/_form.gsp
<%@ page import="com.wdc.SerialServer" %>


<div class="fieldcontain ${hasErrors(bean: serialServerInstance, field: 'ipAddress', 'error')} required">
	<label for="ipAddress">
		<g:message code="serialServer.ipAddress.label" default="Ip Address" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="ipAddress" value="${serialServerInstance?.ipAddress}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: serialServerInstance, field: 'port', 'error')} required">
	<label for="port">
		<g:message code="serialServer.port.label" default="Port" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="port" value="${serialServerInstance?.port}"/>

</div>

AAT_infrastructure/InventoryServer/grails-app/views/serialServer/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'serialServer.label', default: 'SerialServer')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-serialServer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-serialServer" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${serialServerInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${serialServerInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:serialServerInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

AAT_infrastructure/InventoryServer/grails-app/views/serialServer/edit.gsp
<%@ page import="com.wdc.SerialServer" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'serialServer.label', default: 'SerialServer')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-serialServer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-serialServer" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${serialServerInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${serialServerInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:serialServerInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${serialServerInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

AAT_infrastructure/InventoryServer/grails-app/views/serialServer/index.gsp
<%@ page import="com.wdc.SerialServer"%>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName" value="${message(code: 'serialServer.label', default: 'SerialServer')}" />
<title><g:message code="default.list.label" args="[entityName]" /></title>
<g:javascript>
		$( document ).ready(function() {
			//Need to adjust the body size if the table is too large
			var tableWidth = $("#list-serialServer-table").width();
			setBodyWidth(tableWidth);
		});
	</g:javascript>
</head>
<body>
	<a href="#list-serialServer" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
			default="Skip to content&hellip;"
		/></a>
	<div class="nav" role="navigation">
		<ul>
			<li><g:link class="create" action="create">
					<g:message code="default.new.label" args="[entityName]" />
				</g:link></li>
		</ul>
	</div>
	<div id="list-serialServer" class="content scaffold-list" role="main">
		<h1>
			<g:message code="default.list.label" args="[entityName]" />
		</h1>
		<g:if test="${flash.message}">
			<div class="message" role="status">
				${flash.message}
			</div>
		</g:if>
		<table id="list-serialServer-table">
			<thead>
				<tr>
					<g:sortableColumn property="ipAddress" title="${message(code: 'serialServer.ipAddress.label', default: 'Ip Address')}" />
					<g:sortableColumn property="port" title="${message(code: 'serialServer.port.label', default: 'Port')}" />
					<g:sortableColumn property="deviceMacAddress" title="${message(code: 'serialServer.device.label', default: 'Device')}" />
					<g:sortableColumn property="dateCreated" title="${message(code: 'serialServer.dateCreated.label', default: 'Date Created')}" />
					<g:sortableColumn property="lastUpdated" title="${message(code: 'serialServer.lastUpdated.label', default: 'Last Updated')}" />
				</tr>
			</thead>
			<tbody>
				<g:each in="${serialServerInstanceList}" status="i" var="serialServerInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
						<td><g:link action="show" id="${serialServerInstance.id}">
								${fieldValue(bean: serialServerInstance, field: "ipAddress")}
							</g:link></td>
						<td>
							${fieldValue(bean: serialServerInstance, field: "port")}
						</td>
						<td><g:if test="${serialServerInstance?.device}">
								<g:link controller="device" action="show" id="${serialServerInstance.device.id}">
									${fieldValue(bean: serialServerInstance, field: "device.macAddress")}
								</g:link>
							</g:if> <g:else>&nbsp;</g:else></td>
						<td><g:formatDate date="${serialServerInstance.dateCreated}" /></td>
						<td><g:formatDate date="${serialServerInstance.lastUpdated}" /></td>
					</tr>
				</g:each>
			</tbody>
		</table>
		<div class="pagination">
			<g:paginate action="index" total="${instanceCount ?: 0}" />
		</div>
	</div>
</body>
</html>

AAT_infrastructure/InventoryServer/grails-app/views/serialServer/show.gsp
<%@ page import="com.wdc.SerialServer"%>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'serialServer.label', default: 'SerialServer')}" />
<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>
<body>
	<a href="#show-serialServer" class="skip" tabindex="-1"><g:message
			code="default.link.skip.label" default="Skip to content&hellip;" /></a>
	<div class="nav" role="navigation">
		<ul>
			<li><g:link class="list" action="index">
					<g:message code="default.list.label" args="[entityName]" />
				</g:link></li>
			<li><g:link class="create" action="create">
					<g:message code="default.new.label" args="[entityName]" />
				</g:link></li>
		</ul>
	</div>
	<div id="show-serialServer" class="content scaffold-show" role="main">
		<h1>
			<g:message code="default.show.label" args="[entityName]" />
		</h1>
		<g:if test="${flash.message}">
			<div class="message" role="status">
				${flash.message}
			</div>
		</g:if>
		<g:hasErrors bean="${serialServerInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${serialServerInstance}" var="error">
					<li
						<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
							error="${error}" /></li>
				</g:eachError>
			</ul>
		</g:hasErrors>
		<ol class="property-list serialServer">
			<g:if test="${serialServerInstance?.ipAddress}">
				<li class="fieldcontain"><span id="ipAddress-label"
					class="property-label"><g:message
							code="serialServer.ipAddress.label" default="Ip Address" /></span> <span
					class="property-value" aria-labelledby="ipAddress-label"><g:fieldValue
							bean="${serialServerInstance}" field="ipAddress" /></span></li>
			</g:if>

			<g:if test="${serialServerInstance?.port}">
				<li class="fieldcontain"><span id="port-label"
					class="property-label"><g:message
							code="serialServer.port.label" default="Port" /></span> <span
					class="property-value" aria-labelledby="port-label"><g:fieldValue
							bean="${serialServerInstance}" field="port" /></span></li>
			</g:if>

			<g:if test="${serialServerInstance?.device?.macAddress}">
				<li class="fieldcontain"><span id="device.macAddress-label"
					class="property-label"><g:message
							code="serialServer.device.label" default="Device" /></span> <span
					class="property-value" aria-labelledby="device.macAddres-label"><g:link
							controller="device" action="show"
							id="${serialServerInstance.device.id}">
							<g:fieldValue bean="${serialServerInstance}"
								field="device.macAddress" />
						</g:link></span></li>
			</g:if>

			<g:if test="${serialServerInstance?.dateCreated}">
				<li class="fieldcontain"><span id="dateCreated-label"
					class="property-label"><g:message
							code="serialServer.dateCreated.label" default="Date Created" /></span>

					<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate
							date="${serialServerInstance?.dateCreated}" /></span></li>
			</g:if>

			<g:if test="${serialServerInstance?.lastUpdated}">
				<li class="fieldcontain"><span id="lastUpdated-label"
					class="property-label"><g:message
							code="serialServer.lastUpdated.label" default="Last Updated" /></span>

					<span class="property-value" aria-labelledby="lastUpdated-label"><g:formatDate
							date="${serialServerInstance?.lastUpdated}" /></span></li>
			</g:if>

		</ol>
		<g:form url="[resource:serialServerInstance, action:'delete']"
			method="DELETE">
			<fieldset class="buttons">
				<g:link class="edit" action="edit"
					resource="${serialServerInstance}">
					<g:message code="default.button.edit.label" default="Edit" />
				</g:link>
				<g:actionSubmit class="delete" action="delete"
					value="${message(code: 'default.button.delete.label', default: 'Delete')}"
					onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
			</fieldset>
		</g:form>
	</div>
</body>
</html>