AAT_infrastructure/InventoryServer/grails-app/domain/com/wdc/Device.groovy
package com.wdc

class Device {
	String macAddress
	String jenkinsJob
	Boolean isBusy = false
	Boolean isOperational = false
	String internalIPAddress
	String location
	String firmware
	Date dateCreated
	Date lastUpdated
	
	Product product
	PowerSwitch powerSwitch
	SSHGateway sshGateway
	SerialServer serialServer
	

	static mapping = {
		id column:'deviceId'
	}

    static constraints = {
		macAddress(unique:true,shared:"macAddressShared")
		jenkinsJob unique:true,nullable:true
		powerSwitch unique:true, nullable:true
		sshGateway unique:true, nullable:true
		serialServer unique:true, nullable:true
		internalIPAddress unique:true, nullable:true
		location nullable:true
		firmware nullable:true
				
    }
	
	String toString(){
		this.macAddress
	}
	
}

AAT_infrastructure/InventoryServer/grails-app/controllers/com/wdc/DeviceController.groovy
package com.wdc

import com.wdc.response.*
import grails.rest.*
import grails.converters.*
import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class DeviceController extends AbstractInventoryController{
	
	def deviceService
	
	DeviceController(){
		super(Device)
	}

    def show(Device deviceInstance) {
        if(super.show(deviceInstance)){
			def messageResponse = new GetDeviceResponse(status:Status.SUCCESS,device:deviceInstance)
			withFormat{
				html {respond deviceInstance}
				json {render text:messageResponse as JSON,status:OK,contentType:"application/json"}
				xml {render text:messageResponse as XML,status:OK,contentType:"text/xml"}
			}
			
		}
    }

    def create() {
        super.create(new Device(params))
    }

    @Transactional
    def save(Device deviceInstance) {
		if(!super.save(deviceInstance)) return
        
        if(renderErrors(deviceInstance,'create')) return		
		deviceInstance.save flush:true
		if(renderErrors(deviceInstance,'create')) return

		def messageResponse = new GetDeviceResponse(status:Status.SUCCESS,device:deviceInstance)
        withFormat {
            html {
                flash.message = message(code: 'default.created.message', args: [message(code: 'device.label', default: 'Device'), deviceInstance])
                redirect deviceInstance
            }
            json {render text:messageResponse as JSON,status:CREATED,contentType:"application/json"}
			xml {render text:messageResponse as XML,status:CREATED,contentType:"text/xml"}
        }
    }

    def edit(Device deviceInstance) {
        super.edit(deviceInstance)
    }

    @Transactional
    def update(Device deviceInstance) {
		if(!super.update(deviceInstance)) return
        
        if(renderErrors(deviceInstance,'edit')) return
		//Support removing properties via REST calls
		if(deviceInstance.jenkinsJob?.equalsIgnoreCase('null')) deviceInstance.jenkinsJob = null
		if(deviceInstance.internalIPAddress?.equalsIgnoreCase('null')) deviceInstance.internalIPAddress = null
		if(deviceInstance.location?.equalsIgnoreCase('null')) deviceInstance.location = null
		if(deviceInstance.firmware?.equalsIgnoreCase('null')) deviceInstance.firmware = null
				
        deviceInstance.save flush:true
		if(renderErrors(deviceInstance,'edit')) return

		def messageResponse = new GetDeviceResponse(status:Status.SUCCESS,device:deviceInstance)
        withFormat {
            html {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'device.label', default: 'Device'), deviceInstance])
                redirect deviceInstance
            }
            json {render text:messageResponse as JSON,status:OK,contentType:"application/json"}
			xml {render text:messageResponse as XML,status:OK,contentType:"text/xml"}
        }
    }

    @Transactional
    def delete(Device deviceInstance) {
		if(!super.delete(deviceInstance)) return
        
		deviceInstance.delete flush:true
		if(renderErrors(deviceInstance,'show')) return
		
		def messageResponse = new MessageResponse(status:Status.SUCCESS,message:'Device has been successfully deleted')
        withFormat {
            html {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'device.label', default: 'Device'), deviceInstance])
                redirect action:"index", method:"GET"
            }
            json {render text:messageResponse as JSON, status:OK,contentType:"application/json"}
			xml {render text:messageResponse as XML, status:OK,contentType:"text/xml"}
        }
    }
	
	@Transactional
	def checkIn(Device deviceInstance){
		log.debug("Checkin device ${deviceInstance}")
		def messageResponse = deviceService.checkIn(deviceInstance)
		log.debug(messageResponse)
				
		withFormat {
			json {render text:messageResponse as JSON, status:OK,contentType:"application/json"}
			xml {render text:messageResponse as XML, status:OK,contentType:"text/xml"}
			'*' {render text:messageResponse as JSON, status:OK,contentType:"application/json"}
		}
			
	}
	
	@Transactional
	def checkOut(Device deviceInstance){
		log.debug("Checkout device ${deviceInstance},jenkinJob=${params.jenkinsJob},force=${params.force}")
		params.force = params.force ?: "false"
		def messageResponse = deviceService.checkOut(deviceInstance,params.jenkinsJob,Boolean.parseBoolean(params.force))
		log.debug(messageResponse)
				
		withFormat {
			json {render text:messageResponse as JSON, status:OK,contentType:"application/json"}
			xml {render text:messageResponse as XML, status:OK,contentType:"text/xml"}
			'*' {render text:messageResponse as JSON, status:OK,contentType:"application/json"}
		}
		
	}
	
	def isAvailable(Device deviceInstance){
		log.debug("IsAvailable device ${deviceInstance}")
		def messageResponse = deviceService.isAvailable(deviceInstance)
		log.debug(messageResponse)
				
		withFormat {
			json {render text:messageResponse as JSON, status:OK,contentType:"application/json"}
			xml {render text:messageResponse as XML, status:OK,contentType:"text/xml"}
			'*' {render text:messageResponse as JSON, status:OK,contentType:"application/json"}
		}
		
				
	}
	
	def getSSHGateway(Device deviceInstance){
		log.debug("GetSSHGateway device ${deviceInstance}")
		def messageResponse = deviceService.getSSHGateway(deviceInstance)
		log.debug(messageResponse)
			
				
		withFormat {
			json {render text:messageResponse as JSON, status:OK,contentType:"application/json"}
			xml {render text:messageResponse as XML, status:OK,contentType:"text/xml"}
			'*' {render text:messageResponse as JSON, status:OK,contentType:"application/json"}
		}
				
	}
	
	def getSerialServer(Device deviceInstance){
		log.debug("GetSerialServer device ${deviceInstance}")
		def messageResponse = deviceService.getSerialServer(deviceInstance)
		log.debug(messageResponse)
			
				
		withFormat {
			json {render text:messageResponse as JSON, status:OK,contentType:"application/json"}
			xml {render text:messageResponse as XML, status:OK,contentType:"text/xml"}
			'*' {render text:messageResponse as JSON, status:OK,contentType:"application/json"}
		}
				
	}
	
	def getPowerSwitch(Device deviceInstance){
		log.debug("GetPowerSwitch device ${deviceInstance}")
		def messageResponse = deviceService.getPowerSwitch(deviceInstance)
		log.debug(messageResponse)
			
				
		withFormat {
			json {render text:messageResponse as JSON, status:OK,contentType:"application/json"}
			xml {render text:messageResponse as XML, status:OK,contentType:"text/xml"}
			'*' {render text:messageResponse as JSON, status:OK,contentType:"application/json"}
		}
				
	}
	
	def getDeviceByJob(){
		log.debug("GetDeviceByJob jenkinJob=${params.jenkinsJob}")
		def messageResponse = deviceService.getDeviceByJob(params.jenkinsJob)
		log.debug(messageResponse)
				
		withFormat {
			json {render text:messageResponse as JSON, status:OK,contentType:"application/json"}
			xml {render text:messageResponse as XML, status:OK,contentType:"text/xml"}
			'*' {render text:messageResponse as JSON, status:OK,contentType:"application/json"}
		}
	}
	
}

AAT_infrastructure/InventoryServer/grails-app/views/device/_form.gsp
<%@ page import="com.wdc.Device" %>



<div class="fieldcontain ${hasErrors(bean: deviceInstance, field: 'macAddress', 'error')} required">
	<label for="macAddress">
		<g:message code="device.macAddress.label" default="Mac Address" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="macAddress" value="${deviceInstance?.macAddress}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: deviceInstance, field: 'product', 'error')} required">
	<label for="product">
		<g:message code="device.product.label" default="Product" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="product" name="product.id" from="${com.wdc.Product.list()}" optionKey="id" value="${deviceInstance?.product?.id}" required=""  class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: deviceInstance, field: 'jenkinsJob', 'error')} ">
	<label for="jenkinsJob">
		<g:message code="device.jenkinsJob.label" default="Jenkins Job" />
		
	</label>
	<g:textField name="jenkinsJob" value="${deviceInstance?.jenkinsJob}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: deviceInstance, field: 'location', 'error')} ">
	<label for="location">
		<g:message code="device.location.label" default="Location" />
		
	</label>
	<g:textField name="location" value="${deviceInstance?.location}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: deviceInstance, field: 'firmware', 'error')} ">
	<label for="firmware">
		<g:message code="device.firmware.label" default="Firmware" />
		
	</label>
	<g:textField name="firmware" value="${deviceInstance?.firmware}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: deviceInstance, field: 'powerSwitch', 'error')} ">
	<label for="powerSwitch">
		<g:message code="device.powerSwitch.label" default="Power Switch" />
		
	</label>
	<g:select id="powerSwitch" name="powerSwitch.id" from="${com.wdc.PowerSwitch.list()}" optionKey="id" value="${deviceInstance?.powerSwitch?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>

<div class="fieldcontain ${hasErrors(bean: deviceInstance, field: 'sshGateway', 'error')} ">
	<label for="sshGateway">
		<g:message code="device.sshGateway.label" default="Ssh Gateway" />
		
	</label>
	<g:select id="sshGateway" name="sshGateway.id" from="${com.wdc.SSHGateway.list()}" optionKey="id" value="${deviceInstance?.sshGateway?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>

<div class="fieldcontain ${hasErrors(bean: deviceInstance, field: 'serialServer', 'error')} ">
	<label for="serialServer">
		<g:message code="device.serialServer.label" default="Serial Server" />
		
	</label>
	<g:select id="serialServer" name="serialServer.id" from="${com.wdc.SerialServer.list()}" optionKey="id" value="${deviceInstance?.serialServer?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>


<div class="fieldcontain ${hasErrors(bean: deviceInstance, field: 'internalIPAddress', 'error')} ">
	<label for="internalIPAddress">
		<g:message code="device.internalIPAddress.label" default="Internal IP Address" />
		
	</label>
	<g:textField name="internalIPAddress" value="${deviceInstance?.internalIPAddress}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: deviceInstance, field: 'isBusy', 'error')} ">
	<label for="isBusy">
		<g:message code="device.isBusy.label" default="Is Busy" />
		
	</label>
	<g:checkBox name="isBusy" value="${deviceInstance?.isBusy}" />

</div>

<div class="fieldcontain ${hasErrors(bean: deviceInstance, field: 'isOperational', 'error')} ">
	<label for="isOperational">
		<g:message code="device.isOperational.label" default="Is Operational" />
		
	</label>
	<g:checkBox name="isOperational" value="${deviceInstance?.isOperational}" />

</div>

AAT_infrastructure/InventoryServer/grails-app/views/device/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'device.label', default: 'Device')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-device" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-device" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${deviceInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${deviceInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:deviceInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

AAT_infrastructure/InventoryServer/grails-app/views/device/edit.gsp
<%@ page import="com.wdc.Device" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'device.label', default: 'Device')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-device" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-device" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${deviceInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${deviceInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:deviceInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${deviceInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

AAT_infrastructure/InventoryServer/grails-app/views/device/index.gsp
<%@ page import="com.wdc.Device"%>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName" value="${message(code: 'device.label', default: 'Device')}" />
<title><g:message code="default.list.label" args="[entityName]" /></title>
<g:javascript>
		$( document ).ready(function() {
			//Need to adjust the body size if the table is too large
			var tableWidth = $("#list-device-table").width();
			setBodyWidth(tableWidth);
		});
	</g:javascript>
</head>
<body>
	<a href="#list-device" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;" /></a>
	<div class="nav" role="navigation">
		<ul>
			<li><g:link class="create" action="create">
					<g:message code="default.new.label" args="[entityName]" />
				</g:link></li>
		</ul>
	</div>
	<div id="list-device" class="content scaffold-list" role="main">
		<h1>
			<g:message code="default.list.label" args="[entityName]" />
		</h1>
		<g:if test="${flash.message}">
			<div class="message" role="status">
				${flash.message}
			</div>
		</g:if>
		<table id="list-device-table">
			<thead>
				<tr>
					<g:sortableColumn property="macAddress" title="${message(code: 'device.macAddress.label', default: 'Mac Address')}" />
					<g:sortableColumn property="product" title="${message(code: 'device.product.label', default: 'Product')}" />
					<g:sortableColumn property="jenkinsJob" title="${message(code: 'device.jenkinsJob.label', default: 'Jenkins Job')}" />
					<g:sortableColumn property="location" title="${message(code: 'device.location.label', default: 'Location')}" />
					<g:sortableColumn property="firmware" title="${message(code: 'device.firmware.label', default: 'Firmware')}" />
					<g:sortableColumn property="isBusy" title="${message(code: 'device.isBusy.label', default: 'Is Busy')}" />
					<g:sortableColumn property="isOperational" title="${message(code: 'device.isOperational.label', default: 'Is Operational')}" />
					<g:sortableColumn property="internalIPAddress"
						title="${message(code: 'device.internalIPAddress.label', default: 'Internal IP Address')}"
					/>
					<th><g:message code="device.powerSwitch.label" default="Power Switch" /></th>
					<th><g:message code="device.sshGateway.label" default="Ssh Gateway" /></th>
					<th><g:message code="device.serialServer.label" default="Serial Server" /></th>
				</tr>
			</thead>
			<tbody>
				<g:each in="${deviceInstanceList}" status="i" var="deviceInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
						<td><g:link action="show" id="${deviceInstance.id}">
								${fieldValue(bean: deviceInstance, field: "macAddress")}
							</g:link></td>
						<td><g:link controller="product" action="show" id="${deviceInstance.product.id}">
								${fieldValue(bean: deviceInstance, field: "product")}
							</g:link></td>
						<td>
							${fieldValue(bean: deviceInstance, field: "jenkinsJob")}
						</td>
						<td>
							${fieldValue(bean: deviceInstance, field: "location")}
						</td>
						<td>
							${fieldValue(bean: deviceInstance, field: "firmware")}
						</td>
						<td>
							${fieldValue(bean: deviceInstance, field: "isBusy")}
						</td>
						<td>
							${fieldValue(bean: deviceInstance, field: "isOperational")}
						</td>
						<td>
							${fieldValue(bean: deviceInstance, field: "internalIPAddress")}
						</td>
						<td><g:link controller="powerSwitch" action="show" id="${deviceInstance?.powerSwitch?.id}">
								${fieldValue(bean: deviceInstance, field: "powerSwitch")}
							</g:link></td>
						<td><g:link controller="SSHGateway" action="show" id="${deviceInstance?.sshGateway?.id}">
								${fieldValue(bean: deviceInstance, field: "sshGateway")}
							</g:link></td>
						<td><g:link controller="serialServer" action="show" id="${deviceInstance?.serialServer?.id}">
								${fieldValue(bean: deviceInstance, field: "serialServer")}
							</g:link></td>
					</tr>
				</g:each>
			</tbody>
		</table>
		<div class="pagination">
			<g:paginate action="index" total="${instanceCount ?: 0}" />
		</div>
	</div>
</body>
</html>

AAT_infrastructure/InventoryServer/grails-app/views/device/show.gsp
<%@ page import="com.wdc.Device" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'device.label', default: 'Device')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-device" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-device" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${deviceInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${deviceInstance}" var="error">
					<li
						<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
							error="${error}" /></li>
				</g:eachError>
			</ul>
		</g:hasErrors>
			<ol class="property-list device">
			
				<g:if test="${deviceInstance?.macAddress}">
				<li class="fieldcontain">
					<span id="macAddress-label" class="property-label"><g:message code="device.macAddress.label" default="Mac Address" /></span>
					
						<span class="property-value" aria-labelledby="macAddress-label"><g:fieldValue bean="${deviceInstance}" field="macAddress"/></span>
					
				</li>
				</g:if>
				
				<g:if test="${deviceInstance?.product}">
				<li class="fieldcontain">
					<span id="product-label" class="property-label"><g:message code="device.product.label" default="Product" /></span>
					
						<span class="property-value" aria-labelledby="product-label"><g:link controller="product" action="show" id="${deviceInstance?.product.id}">${deviceInstance?.product?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${deviceInstance?.jenkinsJob}">
				<li class="fieldcontain">
					<span id="jenkinsJob-label" class="property-label"><g:message code="device.jenkinsJob.label" default="Jenkins Job" /></span>
					
						<span class="property-value" aria-labelledby="jenkinsJob-label"><g:fieldValue bean="${deviceInstance}" field="jenkinsJob"/></span>
					
				</li>
				</g:if>
				
				<g:if test="${deviceInstance?.location}">
				<li class="fieldcontain">
					<span id="location-label" class="property-label"><g:message code="device.location.label" default="Location" /></span>
					
						<span class="property-value" aria-labelledby="location-label"><g:fieldValue bean="${deviceInstance}" field="location"/></span>
					
				</li>
				</g:if>
				
				<g:if test="${deviceInstance?.firmware}">
				<li class="fieldcontain">
					<span id="firmware-label" class="property-label"><g:message code="device.firmware.label" default="Firmware" /></span>
					
						<span class="property-value" aria-labelledby="firmware-label"><g:fieldValue bean="${deviceInstance}" field="firmware"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${deviceInstance?.powerSwitch}">
				<li class="fieldcontain">
					<span id="powerSwitch-label" class="property-label"><g:message code="device.powerSwitch.label" default="Power Switch" /></span>
					
						<span class="property-value" aria-labelledby="powerSwitch-label"><g:link controller="powerSwitch" action="show" id="${deviceInstance?.powerSwitch?.id}">${deviceInstance?.powerSwitch?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${deviceInstance?.sshGateway}">
				<li class="fieldcontain">
					<span id="sshGateway-label" class="property-label"><g:message code="device.sshGateway.label" default="Ssh Gateway" /></span>
					
						<span class="property-value" aria-labelledby="sshGateway-label"><g:link controller="SSHGateway" action="show" id="${deviceInstance?.sshGateway?.id}">${deviceInstance?.sshGateway?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${deviceInstance?.serialServer}">
				<li class="fieldcontain">
					<span id="serialServer-label" class="property-label"><g:message code="device.serialServer.label" default="Serial Server" /></span>
					
						<span class="property-value" aria-labelledby="serialServer-label"><g:link controller="serialServer" action="show" id="${deviceInstance?.serialServer?.id}">${deviceInstance?.serialServer?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
					
							
				<g:if test="${deviceInstance?.internalIPAddress}">
				<li class="fieldcontain">
					<span id="internalIPAddress-label" class="property-label"><g:message code="device.internalIPAddress.label" default="Internal IPA ddress" /></span>
					
						<span class="property-value" aria-labelledby="internalIPAddress-label"><g:fieldValue bean="${deviceInstance}" field="internalIPAddress"/></span>
					
				</li>
				</g:if>
			

				<li class="fieldcontain">
					<span id="isBusy-label" class="property-label"><g:message code="device.isBusy.label" default="Is Busy" /></span>
					
						<span class="property-value" aria-labelledby="isBusy-label"><g:formatBoolean boolean="${deviceInstance?.isBusy}" /></span>
					
				</li>
				
	
				<li class="fieldcontain">
					<span id="isOperational-label" class="property-label"><g:message code="device.isOperational.label" default="Is Operational" /></span>
					
						<span class="property-value" aria-labelledby="isOperational-label"><g:formatBoolean boolean="${deviceInstance?.isOperational}" /></span>
					
				</li>
	
				
				<g:if test="${deviceInstance?.dateCreated}">
				<li class="fieldcontain">
					<span id="dateCreated-label" class="property-label"><g:message code="device.dateCreated.label" default="Date Created" /></span>
					
						<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${deviceInstance?.dateCreated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${deviceInstance?.lastUpdated}">
				<li class="fieldcontain">
					<span id="lastUpdated-label" class="property-label"><g:message code="device.lastUpdated.label" default="Last Updated" /></span>
					
						<span class="property-value" aria-labelledby="lastUpdated-label"><g:formatDate date="${deviceInstance?.lastUpdated}" /></span>
					
				</li>
				</g:if>
			
				
			
			</ol>
			<g:form url="[resource:deviceInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${deviceInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>