AAT_infrastructure/InventoryServer/grails-app/domain/com/wdc/PowerSwitch.groovy
package com.wdc


class PowerSwitch {
	String ipAddress
	String port
	Date dateCreated
	Date lastUpdated
	
	static transients = ['device']
	
	static mapping = {
		id column:'powerSwitchId'
	}
	
    static constraints = {
		port(unique:"ipAddress",shared:"portShared")
		ipAddress(shared:"ipAddressShared")
    }
	
	Device getDevice() {
		def c = Device.createCriteria()
		def device = c.get {
			powerSwitch {
				eq('id',this.id)
			}
		}
	}
	

	String toString(){		
		"${this.ipAddress}:${this.port}"
	}
	
}

AAT_infrastructure/InventoryServer/grails-app/controllers/com/wdc/PowerSwitchController.groovy
package com.wdc

import com.wdc.response.*
import grails.rest.*
import grails.converters.*
import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class PowerSwitchController extends AbstractInventoryController{
	
	def powerSwitchService
	
	PowerSwitchController(){
		super(PowerSwitch)
	}

    def show(PowerSwitch powerSwitchInstance) {
        if(super.show(powerSwitchInstance)){
			def messageResponse = new GetPowerSwitchResponse(status:Status.SUCCESS,powerSwitch:powerSwitchInstance)
			withFormat{
				html {respond powerSwitchInstance}
				json {render text:messageResponse as JSON,status:OK,contentType:"application/json"}
				xml {render text:messageResponse as XML,status:OK,contentType:"text/xml"}
			}
			
		}
    }

    def create() {
        super.create(new PowerSwitch(params))
    }

    @Transactional
    def save(PowerSwitch powerSwitchInstance) {
		if(!super.save(powerSwitchInstance)) return
                
        if(renderErrors(powerSwitchInstance,'create')) return
        powerSwitchInstance.save flush:true
		if(renderErrors(powerSwitchInstance,'create')) return

		def messageResponse = new GetPowerSwitchResponse(status:Status.SUCCESS,powerSwitch:powerSwitchInstance)
        withFormat {
            html {
                flash.message = message(code: 'default.created.message',args: [message(code: 'powerSwitch.label', default: 'PowerSwitch'), powerSwitchInstance])
                redirect powerSwitchInstance
            }
            json {render text:messageResponse as JSON,status:CREATED,contentType:"application/json"}
			xml {render text:messageResponse as XML,status:CREATED,contentType:"text/xml"}
        }
    }

    def edit(PowerSwitch powerSwitchInstance) {
        super.edit(powerSwitchInstance)
    }

    @Transactional
    def update(PowerSwitch powerSwitchInstance) {
		if(!super.update(powerSwitchInstance)) return
        
        if(renderErrors(powerSwitchInstance,'edit')) return
        powerSwitchInstance.save flush:true
		if(renderErrors(powerSwitchInstance,'edit')) return

		def messageResponse = new GetPowerSwitchResponse(status:Status.SUCCESS,powerSwitch:powerSwitchInstance)
		withFormat {
            html {
                flash.message = message(code: 'default.updated.message',args: [message(code: 'powerSwitch.label', default: 'PowerSwitch'),powerSwitchInstance])
                redirect powerSwitchInstance
            }
            json {render text:messageResponse as JSON,status:OK,contentType:"application/json"}
			xml {render text:messageResponse as XML,status:OK,contentType:"text/xml"}
        }
    }

    @Transactional
    def delete(PowerSwitch powerSwitchInstance) {
		if(!super.delete(powerSwitchInstance)) return
		
        powerSwitchService.delete(powerSwitchInstance)
		if(renderErrors(powerSwitchInstance,'show')) return
		
		def messageResponse = new MessageResponse(status:Status.SUCCESS,message:'Power Switch has been successfully deleted')
        withFormat {
            html {
                flash.message = message(code: 'default.deleted.message',args: [message(code: 'powerSwitch.label', default: 'PowerSwitch'), powerSwitchInstance])
                redirect action:"index", method:"GET"
            }
            json {render text:messageResponse as JSON, status:OK,contentType:"application/json"}
			xml {render text:messageResponse as XML, status:OK,contentType:"text/xml"}
        }
    }
	
}

AAT_infrastructure/InventoryServer/grails-app/views/powerSwitch/_form.gsp
<%@ page import="com.wdc.PowerSwitch" %>


<div class="fieldcontain ${hasErrors(bean: powerSwitchInstance, field: 'ipAddress', 'error')} required">
	<label for="ipAddress">
		<g:message code="powerSwitch.ipAddress.label" default="IP Address" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="ipAddress" value="${powerSwitchInstance?.ipAddress}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: powerSwitchInstance, field: 'port', 'error')} required">
	<label for="port">
		<g:message code="powerSwitch.port.label" default="Port" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="port" pattern="${powerSwitchInstance.constraints.port.matches}" value="${powerSwitchInstance?.port}"/>

</div>

AAT_infrastructure/InventoryServer/grails-app/views/powerSwitch/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'powerSwitch.label', default: 'PowerSwitch')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-powerSwitch" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-powerSwitch" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${powerSwitchInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${powerSwitchInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:powerSwitchInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

AAT_infrastructure/InventoryServer/grails-app/views/powerSwitch/edit.gsp
<%@ page import="com.wdc.PowerSwitch" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'powerSwitch.label', default: 'PowerSwitch')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-powerSwitch" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-powerSwitch" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${powerSwitchInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${powerSwitchInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:powerSwitchInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${powerSwitchInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

AAT_infrastructure/InventoryServer/grails-app/views/powerSwitch/index.gsp
<%@ page import="com.wdc.PowerSwitch"%>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName" value="${message(code: 'powerSwitch.label', default: 'PowerSwitch')}" />
<title><g:message code="default.list.label" args="[entityName]" /></title>
<g:javascript>
		$( document ).ready(function() {
			//Need to adjust the body size if the table is too large
			var tableWidth = $("#list-powerSwitch-table").width();
			setBodyWidth(tableWidth);
		});
	</g:javascript>
</head>
<body>
	<a href="#list-powerSwitch" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
			default="Skip to content&hellip;"
		/></a>
	<div class="nav" role="navigation">
		<ul>
			<li><g:link class="create" action="create">
					<g:message code="default.new.label" args="[entityName]" />
				</g:link></li>
		</ul>
	</div>
	<div id="list-powerSwitch" class="content scaffold-list" role="main">
		<h1>
			<g:message code="default.list.label" args="[entityName]" />
		</h1>
		<g:if test="${flash.message}">
			<div class="message" role="status">
				${flash.message}
			</div>
		</g:if>
		<table id="list-powerSwitch-table">
			<thead>
				<tr>
					<g:sortableColumn property="ipAddress" title="${message(code: 'powerSwitch.ipAddress.label', default: 'IP Address')}" />
					<g:sortableColumn property="port" title="${message(code: 'powerSwitch.port.label', default: 'Port')}" />
					<g:sortableColumn property="deviceMacAddress" title="${message(code: 'powerSwitch.device.label', default: 'Device')}" />
					<g:sortableColumn property="dateCreated" title="${message(code: 'default.date.created.label', default: 'Date Created')}" />
					<g:sortableColumn property="lastUpdated" title="${message(code: 'default.last.updated.label', default: 'Last Updated')}" />
				</tr>
			</thead>
			<tbody>
				<g:each in="${powerSwitchInstanceList}" status="i" var="powerSwitchInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
						<td><g:link action="show" id="${powerSwitchInstance.id}">
								${fieldValue(bean: powerSwitchInstance, field: "ipAddress")}
							</g:link></td>
						<td>
							${fieldValue(bean: powerSwitchInstance, field: "port")}
						</td>
						<td><g:if test="${powerSwitchInstance?.device}">
								<g:link controller="device" action="show" id="${powerSwitchInstance.device.id}">
									${fieldValue(bean: powerSwitchInstance, field: "device.macAddress")}
								</g:link>
							</g:if> <g:else>&nbsp;</g:else></td>
						<td><g:formatDate date="${powerSwitchInstance.dateCreated}" /></td>
						<td><g:formatDate date="${powerSwitchInstance.lastUpdated}" /></td>
					</tr>
				</g:each>
			</tbody>
		</table>
		<div class="pagination">
			<g:paginate action="index" total="${instanceCount ?: 0}" />
		</div>
	</div>
</body>
</html>

AAT_infrastructure/InventoryServer/grails-app/views/powerSwitch/show.gsp
<%@ page import="com.wdc.PowerSwitch" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'powerSwitch.label', default: 'PowerSwitch')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-powerSwitch" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-powerSwitch" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${powerSwitchInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${powerSwitchInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<ol class="property-list powerSwitch">
			
				<g:if test="${powerSwitchInstance?.ipAddress}">
				<li class="fieldcontain">
					<span id="ipAddress-label" class="property-label"><g:message code="powerSwitch.ipAddress.label" default="Ip Address" /></span>
					
						<span class="property-value" aria-labelledby="ipAddress-label"><g:fieldValue bean="${powerSwitchInstance}" field="ipAddress"/></span>
					
				</li>
				</g:if>
				
				<g:if test="${powerSwitchInstance?.port}">
				<li class="fieldcontain">
					<span id="port-label" class="property-label"><g:message code="powerSwitch.port.label" default="Port" /></span>
					
						<span class="property-value" aria-labelledby="port-label"><g:fieldValue bean="${powerSwitchInstance}" field="port"/></span>
					
				</li>
				</g:if>
				
				<g:if test="${powerSwitchInstance?.device?.macAddress}">
				<li class="fieldcontain"><span id="device.macAddress-label"
					class="property-label"><g:message
							code="powerSwitch.device.label" default="Device" /></span> <span
					class="property-value" aria-labelledby="device.macAddres-label"><g:link
							controller="device" action="show"
							id="${powerSwitchInstance.device.id}">
							<g:fieldValue bean="${powerSwitchInstance}"
								field="device.macAddress" />
						</g:link></span></li>
				</g:if>
			
				<g:if test="${powerSwitchInstance?.dateCreated}">
				<li class="fieldcontain">
					<span id="dateCreated-label" class="property-label"><g:message code="default.last.updated.label" default="Date Created" /></span>
					
						<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${powerSwitchInstance?.dateCreated}" /></span>
					
				</li>
				</g:if>
			
			
				<g:if test="${powerSwitchInstance?.lastUpdated}">
				<li class="fieldcontain">
					<span id="lastUpdated-label" class="property-label"><g:message code="default.last.updated.label" default="Last Updated" /></span>
					
						<span class="property-value" aria-labelledby="lastUpdated-label"><g:formatDate date="${powerSwitchInstance?.lastUpdated}" /></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:powerSwitchInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${powerSwitchInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>